#pragma once

enum class TAG_COLLISION
{
    IDLE,
    OBSTACLE,
    BODY_OF_PLAYER_1,
    BODY_OF_PLAYER_2,
    BODY_OF_PLAYER_3,
    BODY_OF_PLAYER_4,
    DAMAGE_OF_PLAYER_1,
    DAMAGE_OF_PLAYER_2,
    DAMAGE_OF_PLAYER_3,
    DAMAGE_OF_PLAYER_4,
};
